"""init

Revision ID: efad7543cd6d
Revises: 5a3b62bbfe61
Create Date: 2026-04-24 09:07:57.362735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad7543cd6d'
down_revision = '5a3b62bbfe61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('part_name', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('revision', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('tolerance', sa.String(length=32), nullable=True),
    sa.Column('cad_file_url', sa.String(length=256), nullable=True),
    sa.Column('model_file_url', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standard', sa.String(length=64), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('project_code', sa.String(length=64), nullable=True),
    sa.Column('drawing_number', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['part_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    op.drop_table('part_categories')
    # ### end Alembic commands ###
